version: 2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    parameters:
      path:
        type: string
      destination:
        type: string
        default: ""
    steps:
      - run:
          command: |
            curl https://ramenipsum.herokuapp.com/paragraphs/1 >> ramen.txt
      - store_artifacts:
          path: ramen.txt
